# Lab 00 - A - Data Analysis In Python - First Steps

Machine learning and data analysis (that is usually also a pre-step for learning) deal with data. Thererefore we need tools to manipulate it and extract the information we want. In the Python environment there are two very useful packages for this: [`numpy`](https://numpy.org/doc/1.19/) and [`pandas`](https://pandas.pydata.org/docs/reference/index.html#api).

In this lab, we will take the first steps into using these packages and see some of their functionalities. These will be needed throughout the course. Both packages contain many useful functionalities, of which we will introduce only a few. To find out more about the other functionalities, the documentations, **Google** and **StackOverflow** are your best friends. 

In [3]:
# Load commonly used imports (such as numpy and pandas) and several utils functions that 
# are used thoughout different labs and code examples

import sys
sys.path.append("../")
from utils import *


# Numpy - The Basics

Let us start with numpy. This package supports vector, matrix and tensor operations over numerical (but not just) data. It is very comfortable and much faster than `for` loops and classic `list` manipulations.

## Array Creation

There are multiple ways to create an array. We can create it from an existing list, load it from a file or generate a new array.


In [4]:
array_1D = np.array([6, 2, 8, 4, 5, 10, 7, 143, 9, 10])
print(array_1D)
print(array_1D.shape)

[  6   2   8   4   5  10   7 143   9  10]
(10,)


In [5]:
array_2D = np.array(
    [[10, 20, 30, 40], 
     [100, 200, 300, 400], 
     [1000, 2000, 3000, 4000]])
print(array_2D)
print(array_2D.shape)

[[  10   20   30   40]
 [ 100  200  300  400]
 [1000 2000 3000 4000]]
(3, 4)


In [6]:
array_3D = np.array(
    [[[10, 20, 30, 40], [100, 200, 300, 400], [1000, 2000, 3000, 4000]],
    [[11, 21, 31, 41], [101, 201, 301, 401], [1001, 2001, 3001, 4001]]])
print(array_3D)
print(array_3D.shape)

[[[  10   20   30   40]
  [ 100  200  300  400]
  [1000 2000 3000 4000]]

 [[  11   21   31   41]
  [ 101  201  301  401]
  [1001 2001 3001 4001]]]
(2, 3, 4)


Using `numpy`'s functions for creating new arrays requires specifying the shape of the desired output array. This is an n-array tuple specifying the sizes of the different dimensions. 

*   Specifying the shape `(3)` will create a 1D array with 3 entries.
*   Specifying the shape `(10, 3)` will create a 2D matrix with 10 rows and 3 columns.
*   Specifying the shape `(10, 28, 28)` will create a 3D matrix (a tensor) which we can think of in the following manner: it is an object holding 10 2D matrices of size 28x28.





In [ ]:
# Initalize arrays with built-in numpy functions
zeros_3D = np.zeros((4, 5, 2)) # Create a 3D arrays of 0's
ones_2D = np.ones((4, 5)) # Create a 2D arrays of 1's
print(zeros_3D)
print(ones_2D)

In [ ]:
np.arange(50) # Create the vector [0, 1, 2, 3, 4, .. , 48, 49]

In [ ]:
# Create a vector of random integers from 5 to 50, with shape (2, 3)
np.random.randint(5, 50, (2, 3))

There are many other functions such as `np.full`, `np.eye`, `np.random.uniform`, etc. Next, let us load an existsing dataset into a numpy array. This specific dataset represents images.

In [7]:
img_array = np.loadtxt(open("../datasets/MNIST_Images.csv", "rb"), delimiter=",").reshape(-1, 28, 28)
img_array.shape

(100, 28, 28)

In [10]:
px.imshow(img_array[8]).show()

## Array indexing and slicing

A great strength of `numpy` is the ease in subsetting an array to retrieve only specific parts of it. We do so by indexing and slicing the arrays. For 1D arrays these operations are very similar to those over lists.  For arrays of higher dimensions, we use a comma to separate the slicing of each dimension. For example, accessing an element in the array `arr` in the first row and second column is done by: `arr[0, 1]` (recall indexing in python begins from zero). To select only the second column, over all rows write: `arr[:, 2]`

In [11]:
array_1D = np.array([10, 11, 12, 13, 14, 15, 16])
# Select 1st element
print("Select 1st element") 
print(array_1D[1])

# Select all the elements from 1st to 4th element
print("\nSelect all the elements from 1st to 4th element") 
print(array_1D[1:5])

# Select elements [1, 4]
print("\nSelect elements [1, 4]")
print(array_1D[[1, 4]])


array_2D = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12],
                     [13, 14, 15, 16],
                     [17, 18, 19, 20]])
# Select 1st row, 2nd column  
print(array_2D[1, 2])


randint_2D = np.random.randint(5, 50, (10, 20))
print("\nPrint random array")
print(randint_2D)

# Select from 3rd row to 5th, all the columns
print("\nSelect from 3rd row to 5th, all the columns")
print(randint_2D[2:5, :])

# Select from 3rd row to 5th, columns 1 and 2
print("\nSelect from 3rd row to 5th, columns 1 and 2")
print(randint_2D[2:5, 1:3])

# Select from 3d row to 5th, columns 3, 5, 6, and  11
print("\nSelect from 3rd row to 5th, columns 3, 5, 6, and  11")
print(randint_2D[2:5, [3, 5, 6, 11]])


Select 1st element
11

Select all the elements from 1st to 4th element
[11 12 13 14]

Select elements [1, 4]
[11 14]
7

Print random array
[[33 18 12 38 34 20 30 45  6 27  6 41  9 49 10 46  9  9 19  6]
 [46  7 27 35 44 18 41  9 36 31  5 36 32 47 32 13 15 35 44 36]
 [11 44 37 27 26 16 13 19 20 30 16 16  7 39 13  5 33  9 48 39]
 [14 28 44 12 20 45 11 48 18 42 28 40 11 32 27 49 41  5 37  9]
 [ 9  5 46 15 46 37 12 11 42 15 25 44 45 18 22 40  6  6 30 14]
 [12 18 23 16 38  8  9 19  6 21 41 10 41 32  7  7 26  7 28  9]
 [37 42 23 22 17 40  9 23 38 16  5 29 23 27 48 48  6 11 22 35]
 [29 30 15 44 14 47 23 16 28 15 43  9 10 34 40 10  5 39 14 27]
 [49 20 16 11 12  5  8 49 47 42  9 16 15 46 41 43 47 33 26 48]
 [38  6 30 11 10 44 35 45 49 33 42 47 42 38 44 13 40 41 35 23]]

Select from 3rd row to 5th, all the columns
[[11 44 37 27 26 16 13 19 20 30 16 16  7 39 13  5 33  9 48 39]
 [14 28 44 12 20 45 11 48 18 42 28 40 11 32 27 49 41  5 37  9]
 [ 9  5 46 15 46 37 12 11 42 15 25 44 45 18 22 40  6  6 30 

## Matrix Operations
Another strength of the `numpy` package is that all matrix operations you can think of (and even more) are already implemented. For example, element-wise addition of scalar, multiplication, powering up a matrix, log-transformations and much more.

As `numpy` overloads the different mathematical operators, it is easy to write mathematical expressions over 2 (or more) vectors/matrices, such as summing or multiplying and also comparing their elements.


In [2]:
# Operations on 1 matrix
A = np.arange(1, 33).reshape(4, 8) # Create an array of numbers from 1 ot 32, and then make a 2d array of 4 rows to 8 columns
print(A)

print("\n\nA + 1:")
print(A + 1)
print("\n2 * A:")
print(2 * A)
print("\nA*A*A:")
print(np.power(A, 3))
print("\nlog(A):")
print(np.log(A))
print("\nA Transpose:")
print(A.transpose()) # also np.transpose(A) and A.T are valid syntaxes
print("\n A > 10:")
print(A > 10)

# Operations on 2 matrices
A = np.arange(6).reshape([2, 3])
B = np.random.randint(1, 10, (2, 3))
print("A")
print(A)
print("\n\nB")
print(B)

print("\nA+B:")
print(A + B) # Equivalent to np.add(a_array, b_array)
print("\n A * B (element-wise multiplication):")
print(np.multiply(A, B))
print("\n AB (matrix multiplication):")
print(A @ B.T) # Equivalent to np.dot(a_array, b_array)

print("\nA > B")
print(A > B)


NameError: name 'np' is not defined

For many `numpy` operations we can specify the `axis` over which to perform the operation:

In [14]:
# Concatenate matrices
print("\nConcatenate 2 arrays by the rows:")
print(np.concatenate((A, B), axis = 0)) # Concatenate rows - look at the shape
print("\nConcatenate 2 arrays by the columns:")
print(np.concatenate((A, B), axis = 1)) # Concatenate columns - look at the shape




Concatenate 2 arrays by the rows:
[[0 1 2]
 [3 4 5]
 [6 5 5]
 [7 6 5]]

Concatenate 2 arrays by the columns:
[[0 1 2 6 5 5]
 [3 4 5 7 6 5]]


##  Basic Statistics

You can easily calculate a lot of basic statistics from an array, such as the sum, mean, variance, maximum, argmax, etc. All of these can be retrieved either over the entire array or over rows/columns.

For each of these functions, you can get the statistic for: 
- the whole array: `np.stat(arr)`
- by row: `np.stat(arr, axis = 1)`
- by column: `np.stat(arr, axis = 0)`

In [15]:
# Basic statistics of a matrix
A = np.arange(6).reshape([2, 3])
print("A")
print(A)

print("\n\nSum of the array")
print(np.sum(A)) # Sum all the matrix (return a scalar)
print("\nSum of the array by column")
print(np.sum(A, axis = 0)) # Sum by column (return a vector)
print("\nSum of the array by row")
print(np.sum(A, axis = 1)) # Sum by row (return a vector)

print("\nMax of each row")
print(np.max(A, axis = 1)) # Max by column (return a vector)

print("\nMax of each column")
print(np.max(A, axis = 0)) # Max by row (return a vector)

print("\nAverage of all the array")
print(np.mean(A))


A
[[0 1 2]
 [3 4 5]]


Sum of the array
15

Sum of the array by column
[3 5 7]

Sum of the array by row
[ 3 12]

Max of each row
[2 5]

Max of each column
[3 4 5]

Average of all the array
2.5


## Sampling From Distributions

`numpy` provides a broad set of distributions to sample from. We will cover this in more depth in lab 2. 

In [16]:
A = np.random.randint(1, 15, size = 20)
print("A")
print(A)

print("\n\nThe values that appear in the array")
print(np.unique(A))
print("\nHow many values are between [0, 5), [5, 10), [10, 15]")
np.histogram(A, bins = [0, 5, 10, 15])

A
[10  9  2  1  2  7  4  3  4 10  5  9  1  1 11 14 13  8  8  9]


The values that appear in the array
[ 1  2  3  4  5  7  8  9 10 11 13 14]

How many values are between [0, 5), [5, 10), [10, 15]


(array([8, 7, 5], dtype=int32), array([ 0,  5, 10, 15]))

## Linear Algebra
One of the most important mathematical fields in machine learning is linear algebra. You can perform many of these operations using `numpy`. You can calculate the eigenvectors of a matrix, or its inverse, the rank of the matrix and so on.

In [17]:
A = np.array([[1., 2.], [3., 4.]])
print("A")
print(A)
print("\n\nInverse of A")
print(np.linalg.inv(A))

B = np.diag((1, 2, 3))
print("\n\nB")
print(B)

eigvalues, eigvectors = np.linalg.eig(B)
print("\neigenvalues, eigenvectors")
print(eigvalues, eigvectors)

print("\nRank of the matrix")
print(np.linalg.matrix_rank(B))


A
[[1. 2.]
 [3. 4.]]


Inverse of A
[[-2.   1. ]
 [ 1.5 -0.5]]


B
[[1 0 0]
 [0 2 0]
 [0 0 3]]

eigenvalues, eigenvectors
[1. 2. 3.] [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Rank of the matrix
3


## Reshaping

You can change the shape of your array, with transpose, flattening, reshape, 
adding a new axis (see `np.newaxis`)



In [19]:
B = np.array([[1, 2, 3], [4, 5, 6]])

print("\n\nB")
print(B)

print("\nFlatten matrix")
print(np.ravel(B))


print("\nTranspose matrix")
print(B.transpose())



B
[[1 2 3]
 [4 5 6]]

Flatten matrix
[1 2 3 4 5 6]

Transpose matrix
[[1 4]
 [2 5]
 [3 6]]


## Sorting

You can sort the matrix by row or by column

In [18]:
B = np.array([[3, 6, 1, 4, 10], [5, 1, 8, 3, 65]])

print("B")
print(B)

print("\n\nSort by row")
print(np.sort(B, axis = 1))


B
[[ 3  6  1  4 10]
 [ 5  1  8  3 65]]


Sort by row
[[ 1  3  4  6 10]
 [ 1  3  5  8 65]]


## Indexing By Condition


In [33]:
A = np.random.randint(1, 30, (5, 4))
print("A")
print(A)

print("\nGet the numbers that are greater than 5:")
print(A[A > 5])

print("\nGet the numbers that are divisible by 4:")
print(np.extract(np.mod(A, 4)==0, A))

A
[[24  5 11  5]
 [ 9 12  6  8]
 [17 13  1 19]
 [16  8  6 19]
 [14 10 29  1]]

Get the numbers that are greater than 5:
[24 11  9 12  6  8 17 13 19 16  8  6 19 14 10 29]

Get the numbers that are divisible by 4:
[24 12  8 16  8]


## Let's practice!

To get you a bit more accustomed to `numpy` you are encouraged to solve the following challenges. If you choose to not solve the following challenges, be sure to understand the solutions. Do not use loops or list comprehensions.



Write a program to create a `7x10` matrix that has `0` and `1` staggered:
```
# 0 1 0 1 0 1 0
# 1 0 1 0 1 0 1
# 0 1 0 1 0 1 0
# 1 0 1 0 1 0 1
```
Hint: use slice operations on different axes.

In [41]:
mat = np.zeros((7, 10))
mat[1::2,::2] = 1
mat[::2,1::2] = 1

print(mat)


[[0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]]


In [35]:
staggered = np.zeros((7, 10))
staggered[::2, 1::2] = 1
staggered[1::2, ::2] = 1

print(staggered)

[[0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]]


Calculate the volume of a cylinder with the following diameters and lengths:


In [43]:
diameters = np.array([1, 3, 5, 2, 4])
lengths = np.array([10, 20, 3, 10, 5])

In [44]:
print(np.array(np.power(diameters/2, 2)*lengths*np.pi))

[  7.85398163 141.37166941  58.90486225  31.41592654  62.83185307]


In [49]:
#Write a function that receives 2 vectors and returns their cartesian product:

def create_cartesian_product(vec1, vec2):
    cart_prod = np.array(vec1,vec2)
    print(cart_prod)




In [50]:
def cartesian_product(vec1, vec2):
    # np.repeat([1, 2, 3], 4) -> [1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3]
    # np.tile([1, 2, 3], 4)   -> [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
    return np.transpose(np.array([np.repeat(vec1, len(vec2)), np.tile(vec2, len(vec1))]))

print(cartesian_product([1, 2, 3], [4, 5, 6, 7]))

[[1 4]
 [1 5]
 [1 6]
 [1 7]
 [2 4]
 [2 5]
 [2 6]
 [2 7]
 [3 4]
 [3 5]
 [3 6]
 [3 7]]


Given an array `a` and a number `n`, find the closest number to `n` in `a`:
```
def find_closest(a, n):
  pass
```

In [60]:
def find_closest(a, n):
    return a[np.argmin(abs(a-n),)]
print(find_closest(np.array([1,3,5,4,8]),-5))


1


In [ ]:
def find_closest(a, n):
  a = np.array(a)
  return a[np.argmin(np.abs(a - n))]
                     
print(find_closest([1, 24, 12, 13, 14], 10))

Check if the sudoku grid is valid:
*   Check that each row contains all the numbers from 1 to 9
*   Check that each column contains all the numbers from 1 to 9
*   Check that each of the 9 non-overlapping `3x3` blocks composing grid contain 1 to 9

You can assume it contains only integers and that the shape of the array is `9x9`
```
def check_sudoku(grid):
  pass
```



In [ ]:
def is_1_to_9(array_):
  # Return True if the array contains all the numbers from 1 to 9, False otherwise
    return np.all(np.sort(array_, axis = None) == np.arange(1, 10))

def check_sudoku(grid):
    def check_block(coords_block):
        return is_1_to_9(grid[coords_block[0]*3 : coords_block[0]*3+3, 
                              coords_block[1]*3 : coords_block[1]*3+3])

    grid = np.array(grid)

    # Check that the grid contains only 1 to 9
    if (not is_1_to_9(np.unique(grid))):
        return False

    # Check that each line/column contains 1 to 9:
    # Sort each column. We expect it to be
    # [[1, 1, 1, 1, 1, 1, 1, 1, 1], [2, 2, 2, 2, 2, 2, 2, 2] ... [9, 9, 9, 9, 9, 9, 9, 9, 9]]
    # Thus we expect the sums of the rows: 1*9, 2*9....
    if  np.any(np.sum(np.sort(grid, axis = 0), axis = 1) != np.arange(1, 10)*9):
        return False

    # Make the same for the columns
    if np.any(np.sum(np.sort(grid.transpose(), axis = 0), axis = 1) != np.arange(1, 10)*9):
        return False


    # 0,0 0,0 0,0    0,1 0,1 0,1    0,2 0,2 0,2
    # 0,0 0,0 0,0    0,1 0,1 0,1    0,2 0,2 0,2
    # 0,0 0,0 0,0    0,1 0,1 0,1    0,2 0,2 0,2
    #
    #
    # 1,0 1,0 1,0    1,1 1,1 1,1    1,2 1,2 1,2
    # 1,0 1,0 1,0    1,1 1,1 1,1    1,2 1,2 1,2
    # 1,0 1,0 1,0    1,1 1,1 1,1    1,2 1,2 1,2
    #
    #
    # 2,0 2,0 2,0    2,1 2,1 2,1    2,2 2,2 2,2
    # 2,0 2,0 2,0    2,1 2,1 2,1    2,2 2,2 2,2
    # 2,0 2,0 2,0    2,1 2,1 2,1    2,2 2,2 2,2


    # For each block of 9, check if it contains all the numbers 1 to 9
    blocks_are_valid = np.apply_along_axis(check_block, 1, cartesian_product([0, 1, 2], [0, 1, 2]))
    return np.all(blocks_are_valid)


Given a matrix, check if some row is a scalar multplication of another
```
def check_dependencies(matrix_):
  pass
```



In [ ]:
def check_dependencies(matrix_):
    def rows_are_dependent(indices):
        if indices[0] == indices[1]:
            return False
        return np.unique(matrix_[indices[0],] / matrix_[indices[1],]).shape[0] == 1

    return np.any(np.apply_along_axis(rows_are_dependent, 1,
                                      cartesian_product(np.arange(matrix_.shape[0]), np.arange(matrix_.shape[0]))))


Write a function that gets a 1D array and check if there is no local extrema point in addition to the global one.
```
def have_an_extrema(array):
  pass
```



In [ ]:
def have_a_maxima(array):
    argmax_arr = np.argmax(array[1:-1]) + 1
    before_max_neg = np.all(array[:argmax_arr - 1] - array[1:argmax_arr] < 0)
    after_max_neg = np.all(array[argmax_arr:-1] - array[argmax_arr + 1:] > 0)
    return before_max_neg and after_max_neg

def have_an_extrema(array):
    # Check if it is a monotonic series
    if np.unique(array[:-1] - array[1:]).shape[0] == 1: return True

    # If there is a minimum, we can look for a maximum in the negated array
    return have_a_maxima(array) or have_a_maxima(-array)


Note that instead of `array[:argmax_arr - 1] - array[1:argmax_arr]`, you could use the `np.diff` function


# Pandas
Until now, we have only looked at numerical data. But in real-world problems, we also have textual and categorical data. To manipulate this type of data, we will use the `pandas` library. One of the basic data structures of `pandas` is called a `DataFrame`. Generally, in a `DataFrame`, each row is a different sample and each column is a feature.

For example, each row can represent a student, with columns of the ID, birthday, and gender of the student. 

`pandas` has a lot of possibilities of which we are going to introduce a very small subset.

## Array Creation

In addition to creating an array from lists or randomly generated data frames, we are going to use an existing dataset of house prices (you will get back to this dataset in excercise 2).

In [61]:
# Load https://www.kaggle.com/c/house-prices-advanced-regression-techniques/data?select=train.csv
df = pd.read_csv('../datasets/house_train.csv', index_col=0)
df.head()

MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
Id                                                                    
1           60       RL         65.0     8450   Pave   NaN      Reg   
2           20       RL         80.0     9600   Pave   NaN      Reg   
3           60       RL         68.0    11250   Pave   NaN      IR1   
4           70       RL         60.0     9550   Pave   NaN      IR1   
5           60       RL         84.0    14260   Pave   NaN      IR1   

   LandContour Utilities LotConfig  ... PoolArea PoolQC Fence MiscFeature  \
Id                                  ...                                     
1          Lvl    AllPub    Inside  ...        0    NaN   NaN         NaN   
2          Lvl    AllPub       FR2  ...        0    NaN   NaN         NaN   
3          Lvl    AllPub    Inside  ...        0    NaN   NaN         NaN   
4          Lvl    AllPub    Corner  ...        0    NaN   NaN         NaN   
5          Lvl    AllPub       FR2  ...        0    NaN   NaN         NaN   

   MiscVal MoSold  YrSold  SaleType  SaleCondition  SalePrice  
Id                                                             
1        0      2    2008        WD         Normal     208500  
2        0      5    2007        WD         Normal     181500  
3        0      9    2008        WD         Normal     223500  
4        0      2    2006        WD        Abnorml     140000  
5        0     12    2008        WD         Normal     250000  

[5 rows x 80 columns]

In [62]:
print("\nRows Names")
print(df.index)
print("\nColumns Names")
print(df.columns)
print("\nDf train shape")
print(df.shape)


Rows Names
Int64Index([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
            ...
            1451, 1452, 1453, 1454, 1455, 1456, 1457, 1458, 1459, 1460],
           dtype='int64', name='Id', length=1460)

Columns Names
Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street', 'Alley',
       'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle',
       'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea',
       'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond',
       'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC',
       'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'Bedroo

## Indexing And Slicing
Just like when using `numpy` you can select a subset of rows and columns. You can do it using indices or using names of the rows and columns. You can easily add a new column based on existing ones.

In [63]:
print("\ndf[['GrLivArea', 'SalePrice', 'BedroomAbvGr']]")
print(df[['GrLivArea', 'SalePrice', 'BedroomAbvGr']]) # Select  GrLivArea columns SalePrice BedroomAbvGr

print("\ndf.loc[3:10,['GrLivArea', 'SalePrice', 'BedroomAbvGr'] ]")
print(df.loc[3:10,['GrLivArea', 'SalePrice', 'BedroomAbvGr'] ])

print("\ndf.iloc[[3, 4, 5]]")
print(df.iloc[[3, 4, 5]])
print("\ndf.iloc[3:10,[6, 7, 8]]")
print(df.iloc[3:10,[6, 7, 8]])


df[['GrLivArea', 'SalePrice', 'BedroomAbvGr']]
      GrLivArea  SalePrice  BedroomAbvGr
Id                                      
1          1710     208500             3
2          1262     181500             3
3          1786     223500             3
4          1717     140000             3
5          2198     250000             4
...         ...        ...           ...
1456       1647     175000             3
1457       2073     210000             3
1458       2340     266500             4
1459       1078     142125             2
1460       1256     147500             3

[1460 rows x 3 columns]

df.loc[3:10,['GrLivArea', 'SalePrice', 'BedroomAbvGr'] ]
    GrLivArea  SalePrice  BedroomAbvGr
Id                                    
3        1786     223500             3
4        1717     140000             3
5        2198     250000             4
6        1362     143000             1
7        1694     307000             3
8        2090     200000             3
9        1774     129900

In [64]:
individual_df = pd.DataFrame(np.array([np.random.randint(2000000, 3000000,50), np.random.uniform(1.50, 1.70, size = 50), np.random.uniform(45, 90, size = 50)]).transpose(), columns=['ID','Height','Weight'])

individual_df["BMI"] = individual_df["Weight"] / individual_df["Height"].pow(2)
print("\nIndividual DF")
print(individual_df.head())


Individual DF
          ID    Height     Weight        BMI
0  2759337.0  1.689432  81.836696  28.672566
1  2263119.0  1.646319  64.442403  23.776269
2  2128694.0  1.639365  77.855486  28.969306
3  2354804.0  1.523136  75.912976  32.721917
4  2836746.0  1.680177  89.569155  31.728418


# Basic Statistics
`pandas` provides different statistical functions over `DataFrame`s.

In [65]:
print("\nMedian of the SalePrice column")
print(df.SalePrice.median())

print("\nSelecting rows by condition")
median_price = df.SalePrice.median()
print(df[df.SalePrice > median_price].head())



Median of the SalePrice column
163000.0

Selecting rows by condition
    MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
Id                                                                    
1           60       RL         65.0     8450   Pave   NaN      Reg   
2           20       RL         80.0     9600   Pave   NaN      Reg   
3           60       RL         68.0    11250   Pave   NaN      IR1   
5           60       RL         84.0    14260   Pave   NaN      IR1   
7           20       RL         75.0    10084   Pave   NaN      Reg   

   LandContour Utilities LotConfig  ... PoolArea PoolQC Fence MiscFeature  \
Id                                  ...                                     
1          Lvl    AllPub    Inside  ...        0    NaN   NaN         NaN   
2          Lvl    AllPub       FR2  ...        0    NaN   NaN         NaN   
3          Lvl    AllPub    Inside  ...        0    NaN   NaN         NaN   
5          Lvl    AllPub       FR2  ...        

## Group-by

When working with data that contains also a categorical feature, we are often interested in performing some kind of calculation over all rows containing the same categorical value. For example, given a data frame of student grades for different courses, we can calculate the students' average grade.

In [ ]:
students_df = pd.DataFrame(np.array([np.random.choice(["Zohar", "Shelly", "Omer", "Avi"],50), np.random.choice(["Linearit", "Intro", "Infi", "Probabilistic"], 50), np.random.randint(80, 101, 50)]).transpose(), columns=['Name','Course','Grade'])
students_df["Grade"] = students_df["Grade"].astype(int)

print("\n\nStudents df")
print(students_df.head())

print("\n\nCalculate average by student and by course")
print(students_df.groupby(['Name', 'Course']).mean().reset_index())

## Sorting
As in `numpy` you can sort data frame based on a column

In [ ]:
students_df.sort_values(by='Grade').head()

## Executing Functions By Columns

In `pandas`, you can select columns and apply functions to them. You also can apply functions by elements.

In [ ]:
df = pd.DataFrame(np.random.randint(1, 10, (5,3)),columns=['col1','col2','col3'])

print("\n\ndf")
print(df)
print("\nCalculate the difference between the min and the max of each column")
print(df.apply(lambda x: x.max() - x.min()))

# Apply by element
print("\nMultiply elements by 100")
print(df.applymap(lambda x:x*100))

print("\n\nIterate over the columns")
print("\n-----------------------")
for key,value in df.iteritems():
   print(key,value)

print("\n\nIterate over the rows")
print("\n-----------------------")
for row_idx,row in df.iterrows():
   print(row_idx,row)

## Merging Data Frames


In [ ]:
# Concatenate data frames
import pandas as pd

# Create 2 data frames
ids_df1 = pd.DataFrame({
        'ID': ['336097897', '32109678', '25976389', '32438509', '36790307'],
         'name': ['Amos', 'Eran', 'Sapir', 'Amichai', 'Hadar'], 
        'gender': ["M", "M", "F", "M", "F"]})

ids_df2 = pd.DataFrame({
        'ID': ['21370565', '34256798', '3908412', '326780578'],
        'name': ['Matan', 'Gabriel', 'Anael', 'Liora'], 
        'gender': ["M", "M", "F", "F"]})

print("\n\ndf1")
print(ids_df1)
print("\ndf2")
print(ids_df2)
print("\n\nJoin the two dataframes along rows:")
concatenate_data = pd.concat([ids_df1, ids_df2])
print(concatenate_data)

In [ ]:
birthdates_id = pd.DataFrame({
        'ID': ['336097897', '32109678', '25976389', '32438509', '36790307', '21370565', '34256798', '3908412', '326780578'],
        'birth_year': [1995, 1996, 1993, 1994, 1997, 1991, 1994, 1992, 1996]})

print("\nNow join the result_data and df_exam_data along ID:")
pd.merge(concatenate_data, birthdates_id, on='ID')

## Let's Practice!

Let us create a table of flight companies' flights. Each row will represent a single flight and will have 3 features: city of departure, city of destination and price. 

Implement a function `create_flight_df` that recieves a collection of cities and creates a dataset of randomly selected flights and a price in the range of 100-400.

```
    def create_flight_df(cities_poss, nrows = 100):
        pass
```

The output data frame must not have more than a single record for any pair of cities. There are no flights from a city to itself.

In [ ]:
import numpy as np
import pandas as pd

def create_flight_df(cities, nrows = 20):
    df = pd.DataFrame([], columns=["Departure", "Destination", "Price"])
    
    while df.shape[0] < nrows:
        dep, dest = np.random.choice(cities, size=2, replace=False)
        price = np.random.randint(100, 400)
        
        if not ((df["Departure"] == dep) & (df["Destination"] == dest)).any():
            df = df.append({"Departure": dep, "Destination": dest, "Price": price}, ignore_index=True)
    return df

cities = ["Beijing", "Moscow", "New-York", "Tokyo", "Paris", "Cairo", "Santiago", "Lima", "Kinshasa", "Singapore", 
          "New-Delhi", "London", "Ankara", "Nairobi", "Ottawa", "Seoul", "Tehran", "Guatemala", "Caracas", "Vienna"]

flights = create_flight_df(cities)
flights.head()

As there are pairs of cities with no direct flight between them, let us find the pairs of cities that have a single connection flight between them and calculate the total price of the flgihts. To do so merge the two data frames. This operation is often referred to as "joining" with the options of inner, outer, left, right and cross joining. For more about merging `pandas` data frames read the [documentation](https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html#database-style-dataframe-or-named-series-joining-merging).

In [ ]:
df = pd.merge(flights, flights, left_on=["Destination"], right_on=["Departure"], how="inner")
df = df[df.Departure_x != df.Destination_y]
df["Total_Price"] = df["Price_x"] + df["Price_y"]

df.head()

Create a data frame with all flights of no connection and single connection.

In [ ]:
flights = flights.append(df[["Departure_x", "Destination_y", "Total_Price"]]\
                         .rename(columns={"Departure_x":"Departure", "Destination_y":"Destination", "Total_Price":"Price"}))
flights

Since now we might have more than one way to flight between each pair of cities, let us find the cheapest flight option, with one connection, between two cities.

In [ ]:
min_by_group = df.groupby(["Departure_x", "Destination_y"], as_index=False)["Total_Price"].min()
min_by_group

And if we want to know on average what is the most expensive city to fly to then:

In [ ]:
mean_by_dest = min_by_group.groupby("Destination_y")["Total_Price"].mean()
expensive_city = mean_by_dest.idxmax()
expensive_city